# Generated by Django 5.0.4 on 2024-05-26 22:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Movie',
            new_name='Moviedata',
        ),
    ]
